sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
